# Generated by Django 4.2 on 2023-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_product_sku_product_supplier_inbound_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound_order',
            old_name='sku',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='inbound_order',
            old_name='order_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='inbound_order',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inbound_order',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
