# Generated by Django 4.2 on 2023-04-13 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0003_rename_sku_inbound_order_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='outbound_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, null=True)),
                ('quantity', models.PositiveSmallIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=50, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.product')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
