# Generated by Django 4.2 on 2023-04-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_outbound_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbound_order',
            options={'verbose_name_plural': 'Inbound Orders'},
        ),
        migrations.AlterModelOptions(
            name='outbound_order',
            options={'verbose_name_plural': 'Outbound Orders'},
        ),
    ]
