# Generated by Django 4.2 on 2023-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_inbound_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound_order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outbound_order',
            name='product',
        ),
        migrations.AddField(
            model_name='inbound_order',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outbound_order',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inbound_order',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inbound_order',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outbound_order',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing')], max_length=20, null=True),
        ),
    ]
